apiVersion: v1
kind: Service
metadata:
  name: elastic-app-service
spec:
  selector:
    app: elastic-app
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-deployment
  labels:
    app: elastic-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic-app
  template:
    metadata:
      name: elastic-app
      labels:
        app: elastic-app
    spec:
      containers:
        - name: elasticsearch-app
          image: ghcr.io/chatgut/elasticsearch-service:main
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: GET_USERS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: custom.users.uri
            - name: ELASTICSEARCH_URI
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: elasticsearch.cluster.uri
      restartPolicy: Always
      