services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch2
    restart: on-failure
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data/
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node

  search-service:
    image: search:1
    ports:
      - "8006:8080"
    restart: on-failure

volumes:
  elastic_data: