apiVersion: v1
kind: Service
metadata:
  name: auth-sql
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3307
  selector:
    app: authservice-mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: authservice-mysql-deployment
spec:
  selector:
    matchLabels:
      app: authservice-mysql
  template:
    metadata:
      labels:
        app: authservice-mysql
    spec:
      containers:
        - name: auth-mysql
          image: mysql:8.4.0
          ports:
            - containerPort: 3307
          env:
            - name: MYSQL_DATABASE
              value: authservice-mysql
            - name: MYSQL_USER
              value: developer
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_ROOT_HOST
              value: '%'
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_HOST
              value: '%'
          volumeMounts:
            - name: db-auth-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: db-auth-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
  serviceName: auth-mysql