apiVersion: v1
kind: Service
metadata:
  name: post-service
spec:
  type: ClusterIP
  selector:
    app: post
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-dep
  labels:
    app: post-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      name: post
      labels:
        app: post
    spec:
      containers:
        - name: post
          image: ghcr.io/chatgut/micropostservice:main
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: ROCKET_DATABASES
              value: '{postservice={url="mongodb://postmongo:27017"}}'
            - name: ROCKET_RABBIT_HOST
              value: "amqp://QueueRabbitMQ:5672"
      restartPolicy: Always
      