apiVersion: v1
kind: Service
metadata:
  name: users-sql-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: userservice-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-mysql-deployment
  labels:
    app: users-mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice-mysql
  template:
    metadata:
      name: userservice-mysql
      labels:
        app: userservice-mysql
    spec:
      containers:
        - name: users-mysql
          image: mysql:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_HOST
              value: '%'
            - name: MYSQL_ROOT_USER
              value: root
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: userService
            - name: MYSQL_USER
              value: developer
            - name: MYSQL_PASSWORD
              value: password
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-dbusers-claim
      restartPolicy: Always
      