apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-dbusers
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /run/desktop/mnt/host/c/mnt/userdata/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dbusers-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi