apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-dbdata
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /run/desktop/mnt/host/c/mnt/rabbitdata/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-dbdata-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi