apiVersion: v1
kind: Service
metadata:
  name: rabbit-service
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 15672
      targetPort: 15672
      name: rabbit-port-one
    - protocol: TCP
      port: 5672
      targetPort: 5672
      name: rabbit-port-two
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-dep
  labels:
    app: rabbit-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      name: rabbitmq
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 15672
            - containerPort: 5672
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-dbData
      