apiVersion: v1
kind: Service
metadata:
  name: image-service
spec:
  type: ClusterIP
  selector:
    app: image
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-deployment
  labels:
    app: image-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image
  template:
    metadata:
      name: image
      labels:
        app: image
    spec:
      containers:
        - name: image
          image: ghcr.io/chatgut/imageservicebov:sha-925024f
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8002
              protocol: TCP
          env:
            - name: DB_URL
              value: image-sql-service:3306/imageservice
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: password
      restartPolicy: Always
      