name: Publish image to docker

on:
  push:
    branches:
      - main

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: | 
          docker build . -t frelund/searchapp:latest
      - name: publish
        run: |
          docker push frelund/searchapp:latest
